
name: Test GH Concurrency
run-name: "App: ${{ inputs.appName }}"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.appName }}
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      appName:
        type: choice
        description: 'App you want to deploy'
        options: 
        - busybox
        - nginx
        required: true
        default: 'busybox'
jobs:
  setup-runner:
    name: "First Job"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}
      
      - name: my-step
        run: echo "Hello World!"
